### PR TITLE
merge inject and rename chain elements

### LINKED ISSUE #102: Reorder inject, rename chain elements
# Issue
Existing `inject`, `rename` chain elements makes possible to use them in chain only as:
```
... -> rename -> ... -> inject -> ...
```
It results in issue when multiple clients request for the same kernel interface name and some of them fail.
# Expected solution
Rework these elements so it will be possible to use them in reversed order (even if **only** in reversed order).
```
... -> inject -> ... -> rename -> ...
```

### PR DESCRIPTION
**Pull request by pperiyasamy**
Fixes #102 

Signed-off-by: Periyasamy Palanisamy <periyasamy.palanisamy@est.tech>

### CODE REVIEW

File: pkg/kernel/networkservice/inject/common.go [hunk 1]
```diff
@@ -61,16 +79,57 @@ func move(logger log.Logger, conn *networkservice.Connection, isMoveBack bool) e
...
+
+func moveToContNetNS(vfConfig *vfconfig.VFConfig, ifName string, curNetNS, targetNetNS netns.NsHandle) (err error) {
+	link, _ := kernellink.FindHostDevice("", ifName, targetNetNS)
+	if link != nil {
+		return
+	}
+	if vfConfig != nil && vfConfig.VFInterfaceName != ifName {
+		err = moveInterfaceToAnotherNamespace(vfConfig.VFInterfaceName, curNetNS, curNetNS, targetNetNS)
+		if err == nil {
+			err = renameInterface(vfConfig.VFInterfaceName, ifName, curNetNS, targetNetNS)
```
Comment (Bolodya1997) [inline pkg/kernel/networkservice/inject/common.go:107]: Looks like we need to move interface back in such case.

File: pkg/kernel/networkservice/inject/common.go [hunk 2]
```diff
@@ -61,16 +79,57 @@ func move(logger log.Logger, conn *networkservice.Connection, isMoveBack bool) e
...
+		if strings.Contains(err.Error(), "Link not found") {
+			return nil
+		}
 		return err
 	}
-	logger.Infof("moved network interface %s into the target namespace for connection %s", ifName, conn.GetId())
 	return nil
 }
+
+func moveToContNetNS(vfConfig *vfconfig.VFConfig, ifName string, curNetNS, targetNetNS netns.NsHandle) (err error) {
```
Comment (Bolodya1997) [inline pkg/kernel/networkservice/inject/common.go:99]: Please rename here `curNetNS` to `hostNetNS` and `targetNetNS` to `conNetNS` if you make such renaming.

File: pkg/kernel/networkservice/inject/common.go [hunk 3]
```diff
@@ -61,16 +79,57 @@ func move(logger log.Logger, conn *networkservice.Connection, isMoveBack bool) e
...
+		}
+	} else {
+		err = moveInterfaceToAnotherNamespace(ifName, curNetNS, curNetNS, targetNetNS)
+	}
+	return
+}
+
+func moveToHostNetNS(vfConfig *vfconfig.VFConfig, ifName string, curNetNS, targetNetNS netns.NsHandle) (err error) {
+	if vfConfig != nil && vfConfig.VFInterfaceName != ifName {
+		link, _ := kernellink.FindHostDevice("", vfConfig.VFInterfaceName, curNetNS)
```
Comment (Bolodya1997) [inline pkg/kernel/networkservice/inject/common.go:117]: If interface was renamed, we need to find it by `ifName` and so if we are moving it back, we probably need to find it in `targetNetNS`.

File: pkg/kernel/networkservice/inject/server.go [hunk 4]
```diff
@@ -45,32 +45,30 @@ func (s *injectServer) Request(ctx context.Context, request *networkservice.Netw
...
+	if err := move(ctx, request.GetConnection(), false); err != nil {
 		return nil, err
 	}
 
 	conn, err := next.Server(ctx).Request(ctx, request)
 	if err != nil {
-		err = move(logger, request.GetConnection(), true)
-		if err != nil {
-			logger.Warnf("server request failed, failed to move back the interface: %v", err)
+		moveRenameErr := move(ctx, request.GetConnection(), true)
```
Comment (Bolodya1997) [inline pkg/kernel/networkservice/inject/server.go:54]: Please use here `isEstablished` check as we discussed offline.

File: pkg/kernel/networkservice/inject/common.go (hunk 1 above)
Comment (Bolodya1997) [reply pkg/kernel/networkservice/inject/common.go:107]: I am afraid that this operation is not idempotent, because after the rename we still have different `vfconfig.VFInterfaceName` and `ifName`, but interface is no more accessible by `vfconfig.VFInterfaceName` because it was renamed.

Comment (pperiyasamy) [reply pkg/kernel/networkservice/inject/common.go:107]: yes, that's why there is a check at line 100-103 to see ifName is already present in contNetNS and if interface is already present, it's returned immediately without an error.

File: pkg/kernel/networkservice/inject/common.go (hunk 3 above)
Comment (pperiyasamy) [reply pkg/kernel/networkservice/inject/common.go:117]: This method gets executed only for sriov device move back scenario and renaming would happen only at line 123. 
This check is done to make things to be idempotent and also to find out if sriov device is accidentally moved out to hostNetNS without renaming the interface (in case of container kill), its not appropriate to rely on `ifName` here as multiple NSCs use same interface name. so we must also search using `kernellink.FindHostDevice` using VFs pci address to restore interface original name. will revisit here once this [PR](https://github.com/networkservicemesh/sdk-kernel/pull/307) is merged.

File: pkg/kernel/networkservice/inject/server.go (hunk 4 above)
Comment (pperiyasamy) [reply pkg/kernel/networkservice/inject/server.go:54]: done

File: pkg/kernel/networkservice/inject/common.go (hunk 2 above)
Comment (pperiyasamy) [reply pkg/kernel/networkservice/inject/common.go]: done

**Review by Bolodya1997 — APPROVED** [review]
